OSL Script
Game: DR1

Fade in from black for 0 frames
Music|0, 0, 0

SpiralBridge: Synchronise, %FIRST_SYNC_VALUE
Wait for %FRAMES_BETWEEN_VALUES frames

SpiralBridge: Synchronise, %SECOND_SYNC_VALUE
Wait for %FRAMES_BETWEEN_VALUES frames

SpiralBridge: Synchronise, %THIRD_SYNC_VALUE
Wait for %FRAMES_BETWEEN_VALUES frames

SpiralBridge: Synchronise, %FOURTH_SYNC_VALUE
Wait for %FRAMES_BETWEEN_VALUES frames

Script|%FILE_CHAPTER, %FILE_SCENE, %FILE_ROOM
Stop Script|