OSL Script
Game: DR1

Fade in from black for 0 frames
Music|0, 0, 0

Text|%FIRST_SYNC_TEXT
Wait for %FRAMES_BETWEEN_VALUES frames

Text|%SECOND_SYNC_TEXT
Wait for %FRAMES_BETWEEN_VALUES frames

Text|%THIRD_SYNC_TEXT
Wait for %FRAMES_BETWEEN_VALUES frames

Text|%FOURTH_SYNC_TEXT
Wait for %FRAMES_BETWEEN_VALUES frames

Wait for SpiralBridge ServerAck

Text|[Empty]

Script|%FILE_CHAPTER, %FILE_SCENE, %FILE_ROOM
Stop Script|